/**
 * PayPal Sandbox credentials
 *
 * ⚠️ EDIT THIS FILE ONLY: functions/src/paypalConfig.ts
 * Do NOT edit lib/paypalConfig.js – that file is auto-generated by "npm run build"
 * and will be overwritten, so your changes there will disappear.
 *
 * Get credentials: https://developer.paypal.com/ → Apps & Credentials → Sandbox app
 */

export const PAYPAL_CLIENT_ID = "ASRcdN7zWp3wsxwVNfDMHarn_i2p0C2XoUQKxDrfnGSA168InL_UT0YF79T5WZw_A_SiZ-D3OabY-Hwk";
export const PAYPAL_CLIENT_SECRET = "EOJJPE2pyOePz4KB1c5qY6KrIuiYJXTOQXpHE1_RjRuLpCK_ilBI2wo2CNx85HnZAPr6bTc2MawVKTWg";
