// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLuSo4LLFWgbU6N0wAVBxHct-CBS8Z3g',
    appId: '1:72494482660:web:3a3c562ef28171c6fa98f1',
    messagingSenderId: '72494482660',
    projectId: 'vanguard-7ad09',
    authDomain: 'vanguard-7ad09.firebaseapp.com',
    storageBucket: 'vanguard-7ad09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_llVfQtCPmgIPJiUuewxwyGUT7MYBiI',
    appId: '1:72494482660:android:79a63fba0806bc39fa98f1',
    messagingSenderId: '72494482660',
    projectId: 'vanguard-7ad09',
    storageBucket: 'vanguard-7ad09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUOMLNx29oUUypb7wY4jyEMR12PaNwdA',
    appId: '1:72494482660:ios:98e06d921f49a49ffa98f1',
    messagingSenderId: '72494482660',
    projectId: 'vanguard-7ad09',
    storageBucket: 'vanguard-7ad09.firebasestorage.app',
    iosBundleId: 'com.example.vanguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUOMLNx29oUUypb7wY4jyEMR12PaNwdA',
    appId: '1:72494482660:ios:98e06d921f49a49ffa98f1',
    messagingSenderId: '72494482660',
    projectId: 'vanguard-7ad09',
    storageBucket: 'vanguard-7ad09.firebasestorage.app',
    iosBundleId: 'com.example.vanguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLuSo4LLFWgbU6N0wAVBxHct-CBS8Z3g',
    appId: '1:72494482660:web:e9e969eec69d4ad2fa98f1',
    messagingSenderId: '72494482660',
    projectId: 'vanguard-7ad09',
    authDomain: 'vanguard-7ad09.firebaseapp.com',
    storageBucket: 'vanguard-7ad09.firebasestorage.app',
  );

}